spring.application.name=spring_thymleaf

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=true

mybatis.mapper-locations=classpath:mapper/**/*.xml

#파일업로드 관련설정
#MultipartFile의 사용 여부
spring.servlet.multipart.enabled=true
#파일 하나의 최대 크기를 설정
spring.servlet.multipart.max-file-size=10MB
#업로드 데이터들의 총 크기 설정(<form>의 모든 Controll들의 합 : 입력값의 합)
spring.servlet.multipart.max-request-size=100MB
#업로드되는 파일의 저장되는 경로(설정하지 않으면 OS마다 사용되는 임시경로에 저장)
spring.servlet.multipart.location=c:/dev/upload